# Generated by Django 2.0.4 on 2018-06-03 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_kochbuch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.ManyToManyField(editable=False, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
