# Generated by Django 2.0.4 on 2018-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0004_auto_20180603_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='repose_time_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='working_time_min',
            field=models.IntegerField(default=0),
        ),
    ]
