# Generated by Django 2.0.4 on 2018-06-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0005_auto_20180603_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like',
        ),
    ]
