# Generated by Django 2.0.4 on 2018-06-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0006_remove_recipe_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='app_kochbuch.Recipe'),
        ),
    ]
