# Generated by Django 2.0.4 on 2018-06-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0009_auto_20180606_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='app_kochbuch.Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='app_kochbuch.Severity'),
        ),
    ]
