# Generated by Django 2.0.4 on 2018-06-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0011_auto_20180606_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
