# Generated by Django 2.0.4 on 2018-06-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0014_auto_20180606_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_unit', to='app_kochbuch.Unit'),
        ),
    ]
