# Generated by Django 2.0.4 on 2018-06-06 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0016_auto_20180606_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_severity', to='app_kochbuch.Severity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
