# Generated by Django 2.0.4 on 2018-06-09 17:01

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0019_auto_20180608_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1)]),
        ),
    ]
