# Generated by Django 2.0.4 on 2018-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0020_auto_20180609_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='severity',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='severity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
