# Generated by Django 2.0.4 on 2018-06-09 17:26

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0021_auto_20180609_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='number',
            field=models.FloatField(default=0, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
    ]
