# Generated by Django 2.0.4 on 2018-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0023_auto_20180609_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
