# Generated by Django 2.0.4 on 2018-06-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kochbuch', '0024_auto_20180609_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_image'),
        ),
    ]
